Support compiling mainline kernel from local git repository
* `pmbootstrap init` allows to specify a local linux kernel repository
* New `--local-src` parameter for `pmbootstrap build`:
  `pmbootstrap build linux-postmarketos-mainline --arch=armhf --local-src`
  - Mounts the kernel source to /mnt/pmbootstrap-local-src inside the
    chroot
  - exports `PMB_LOCAL_SRC=/mnt/pmbootstrap-local-src` to `abuild`
* `pmb/helpers/frontend.py`: Verifies, that the packages passed to
  `pmbootstrap build` use `PMB_LOCAL_SRC` when `--local-src` is
  specificed and raise an exception if they don't
* linux-postmarketos-mainline APKBUILD adjustments:
  - update linux-v4.14-v4.15-rc6.patch checksum to upstream (they
    probably updated their git/patch tool, which caused a different
    checksum)
  - fetch(): don't download anything when using `--local-src`
  - unpack(): don't extract anything, but create a link to
    `$PMB_LOCAL_SRC` if it is specified
  - prepare(): don't apply any patches to the kernel source folder
    when using `--local-src`
  - package(): change the `pkgdesc` when using `--local-src`

diff --git a/aports/main/linux-postmarketos-mainline/APKBUILD b/aports/main/linux-postmarketos-mainline/APKBUILD
--- a/aports/main/linux-postmarketos-mainline/APKBUILD
+++ b/aports/main/linux-postmarketos-mainline/APKBUILD
@@ -45,27 +45,47 @@ HOSTCC="${HOSTCC#${CROSS_COMPILE}}"
 
 ksrcdir="$srcdir/linux-$_basever"
 
-prepare() {
-	local _patch_failed=
-	cd "$ksrcdir"
-	# first apply patches in specified order
-	for i in $source; do
-		case $i in
-		*.patch|*.patch::*)
-			_patch=${i%::*}
-			msg "Applying $_patch..."
-			if ! patch -s -p1 -N -i "$srcdir"/$_patch; then
-				echo $_patch >>failed
-				_patch_failed=1
-			fi
-			;;
-		esac
-	done
+fetch() {
+	if [ -z "$PMB_LOCAL_SRC" ]; then
+		default_fetch
+	else
+		mkdir -p "$srcdir"
+		ln -svf "$startdir/$_config" "$srcdir/$_config"
+	fi
+}
 
-	if ! [ -z "$_patch_failed" ]; then
-		error "The following patches failed:"
-		cat failed
-		return 1
+unpack() {
+	if [ -z "$PMB_LOCAL_SRC" ]; then
+		default_unpack
+	else
+		msg "Using local kernel sources: $PMB_LOCAL_SRC"
+		ln -sv "$PMB_LOCAL_SRC" "$ksrcdir"
+	fi
+}
+
+prepare() {
+	if [ -z "$PMB_LOCAL_SRC" ]; then
+		local _patch_failed=
+		cd "$ksrcdir"
+		# first apply patches in specified order
+		for i in $source; do
+			case $i in
+			*.patch|*.patch::*)
+				_patch=${i%::*}
+				msg "Applying $_patch..."
+				if ! patch -s -p1 -N -i "$srcdir"/$_patch; then
+					echo $_patch >>failed
+					_patch_failed=1
+				fi
+				;;
+			esac
+		done
+
+		if ! [ -z "$_patch_failed" ]; then
+			error "The following patches failed:"
+			cat failed
+			return 1
+		fi
 	fi
 
 	mkdir -p "$srcdir"/build
@@ -92,6 +112,11 @@ build() {
 }
 
 package() {
+	if ! [ -z "$PMB_LOCAL_SRC" ]; then
+		pkgdesc="LOCAL KERNEL SOURCE USED"
+		msg "Set pkgdesc to: $pkgdesc"
+	fi
+
 	cd "$srcdir/build/arch/${_carch}/boot"
 
 	if [ "$CARCH" == "aarch64" ]; then
@@ -172,7 +197,7 @@ dev() {
 		"$subpkgdir"/lib/modules/${_abi_release}/build
 }
 sha512sums="77e43a02d766c3d73b7e25c4aafb2e931d6b16e870510c22cef0cdb05c3acb7952b8908ebad12b10ef982c6efbe286364b1544586e715cf38390e483927904d8  linux-4.14.tar.xz
-b68965ef7b78ed9a0547d3a00432b0afaa8441a77412026c84d9b91b751f62d54cb263ec0ffc3547196038f0fe39bdcdfd1e7535776dc8f7a139528ea8ce3dcc  linux-v4.14-v4.15-rc6.patch
+6697b2d8507d0740ff88106811d8fdb5191a63bf073a0bd40ae8d8ba32c3534fd3d011f9ecac0ea9b4111250b1175b792bef3f0a52ea3d8c75bb8fa05e65035f  linux-v4.14-v4.15-rc6.patch
 a75225750193cf31c8b6c15e7748699f842ecadc9ed573f0b10f42bb5343b4e092bcb65b359d170a42a102a4ddfe09d63c1d67550f4b99c29295fa22e1d7b995  config-postmarketos-mainline.armhf
 6310035a0a4c028cc98cab92919cca54be9b79ee9fe63211e7a05876d7befdbd8506a2f80548e228e014e99b0f91f63946352789d8d2f2134c66914163f66ab3  config-postmarketos-mainline.aarch64
 3d42c60061d12a436d19ffdf00623ea71ca31f16f690ae82ebf872d35177c283b4038cd5e270f4e610d6cf6861cef73ac63c995f1f4cfe9d6f2a4a8648ba28fb  config-postmarketos-mainline.x86_64
